config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # match 'hoge' => 'class#method'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def new
    end

    def show
        @task = Task.find(params[:id])
    end

    def create
        @task = Task.new(params.require(:task).permit(:title))
        @task.save
        redirect_to @task
    end

   private
    def task_param
        params.require(:todo).permit(:title)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>id</th>
    <th>Title</th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.title %></td>
      <td><%= link_to 'Show', task_path(task) %></td>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<%= form_with scope: :task, url: tasks_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<p>
  <strong>id:</strong>
  <%= @task.id %>
</p>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My TodoList', controller: 'tasks' %>